### ISSUE TITLE
Checking sig can result in 500 server error

### ISSUE THREAD

**Issue by LunarTwilight** [AntiCompositeNumber/signatures#10]
For example: https://signatures.toolforge.org/check/eo.wikipedia.org/WMFOffice

Also trying to check a wiki that doesn't exist: https://signatures.toolforge.org/check/abcde.wikipedia.org/WMFOffice

**Comment by AntiCompositeNumber** [comment]
https://eo.wikipedia.org/w/index.php?title=MediaWiki%3ASignature&action=raw 404s, raising an exception in the default sig handler.
