### ISSUE TITLE
Add support for wikitech (and possibly other special wikis)

### ISSUE THREAD

**Issue by LunarTwilight** [AntiCompositeNumber/signatures#11]
Could wikitech (and other special wikis) please be added so that they can be checked?

**Comment by AntiCompositeNumber** [comment]
Nope. The site list on https://signatures.toolforge.org/check contains the sites with a database replica. Wikitech does not have a Toolforge replica database because it is disconnected from that infrastructure for stability reasons. The other wikis not listed are private.
